jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - run: |
          pyinstaller --onedir --windowed main.py \
            --add-data "README.md:." \
            --add-data "img:img" \
            --add-data "interface:interface" \
            --add-data "src:src"

      # Linux/macOS
      - name: Package zip (Unix)
        if: runner.os != 'Windows'
        run: |
          zip -r proyecto-${{ matrix.os }}.zip dist/main
          shasum -a 256 proyecto-${{ matrix.os }}.zip > proyecto-${{ matrix.os }}.sha256

      # Windows
      - name: Package zip (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell Compress-Archive -Path dist\main -DestinationPath proyecto-windows.zip
          powershell Get-FileHash proyecto-windows.zip -Algorithm SHA256 | Format-List > proyecto-windows.sha256

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            proyecto-${{ matrix.os }}.zip
            proyecto-${{ matrix.os }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
